spring:
  application:
    name: core-service
  cloud:
    vault:
      uri: ${VAULT_ADDR:http://127.0.0.1:8200}
      authentication: TOKEN
      token: ${VAULT_TOKEN:}
  config:
    import:
      - optional:vault://secret/erp/${SPRING_VAULT_ENV:dev}/common
      - optional:vault://secret/erp/${SPRING_VAULT_ENV:dev}/core-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://local-locust-23592.j77.aws-us-west-2.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full}
    username: ${DATABASE_USER:ai}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_core_org_schema_history
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: ${SERVER_PORT:8084}

app:
  jwt:
    issuer: ${JWT_ISSUER:erp-iam}
    audience: ${JWT_AUDIENCE:erp-api}
    hmac-secret: ${JWT_SECRET:}
  gateway:
    trust-secret: ${GATEWAY_TRUST_SECRET:}
